chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.index, name='index'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'
urlpatterns = [
    path('', views.item, name='item'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'mainpage'
urlpatterns = [
    path('', views.index, name='mainpage'),
]

pengiriman/urls.py
from django.urls import path
from . import views

app_name = 'pengiriman'
urlpatterns = [
    path('daftar_pengiriman', views.kirim_list, name='kirim_list')
]

profil/urls.py
from django.urls import path

from . import views

app_name = 'profil'
urlpatterns = [
    path('', views.profil, name='profil'),
]

toysrent/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('pengiriman/', include('pengiriman.urls')),
    path('chat/', include('chat.urls', namespace="chat")),
    path('barang/', include('barang.urls', namespace="barang")),
    path('item/', include('item.urls')),
    path('profil/', include('profil.urls')),
]

templates/partials/footer.html
{% load static %}

<div class="footer bg-dark">
	<p>CopyRight © 2018 Toysrent E-11</p>
</div>

templates/partials/header.html
{% load static %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
        <a class="navbar-brand" href="{% url 'mainpage:mainpage' %}">
            <img src="https://toys-on-rent.com/images/tor_logo_home_main.gif" alt=""  style="width: 150px; height: 50px">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'item:item' %}">Item</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'barang:index' %}">Barang</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#pesanan">Pesanan</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pengiriman:kirim_list' %}">Pengiriman</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#level">Level</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'chat:index' %}">Chat</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'profil:profil' %}">Profil</a>
                </li>
            </ul>
        </div>
    </nav>

templates/partials/source.html
{% load static %}

<title>Toys Rent</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.colVis.min.js"></script>   
<link rel="stylesheet" href="css/bootstrap-multiselect/bootstrap-multiselect.css" type="text/css">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>